name: Fetch Soccerverse Tactics

on:
  workflow_dispatch:
    inputs:
      season_id:
        description: "Season ID"
        default: "2"
        required: true
      leagues_csv:
        description: "CSV leagues (leave empty to use the built-in default list)"
        default: ""
        required: false
      refresh_days:
        description: "Re-scan window for played fixtures"
        default: "14"
        required: true
  schedule:
    - cron: "0 6 * * 0"   # Tous les dimanches à 06:00 UTC

concurrency:
  group: fetch-tactics
  cancel-in-progress: false

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    env:
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_SERVICE_ROLE: ${{ secrets.SUPABASE_SERVICE_ROLE }}
      SEASON_ID: ${{ inputs.season_id }}
      LEAGUES_CSV: ${{ inputs.leagues_csv }}
      REFRESH_DAYS: ${{ inputs.refresh_days }}
      PAR: "4"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('script/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r script/requirements.txt

      - name: Run fetcher
        run: |
          python script/fetch_tactics.py
          # Remarques :
          # - Sans args => utilise DEFAULT_LEAGUES + SEASON_ID/env (2)
          # - Pour forcer les ligues : ajoutez --leagues "548,549"
          # - Pour plus de verbosité : ajoutez 'set -x' au début
